# Generated by Django 3.0.4 on 2020-04-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('image_link', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year_of_creation', models.DateField()),
                ('image_link', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image_link', models.CharField(default='', max_length=200)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Book')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Creature')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorCreature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Author')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Creature')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Book')),
            ],
        ),
    ]
