# Generated by Django 3.0.4 on 2020-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(null=True),
        ),
    ]
