# Generated by Django 3.0.4 on 2020-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_auto_20200430_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_creation',
            field=models.IntegerField(),
        ),
    ]
